### ISSUE TITLE
Execa usage error

### ISSUE THREAD

**Issue by Apollon77** [esm2cjs/.github#4]
I tried to replace it in adapter-dev from iobroker ... 

So I adjusted the import to:

```
import execa, { ExecaChildProcess } from "@esm2cjs/execa";
```

TS now has issues:
![IMAGE 2022-09-12 18:15:41](https://user-images.githubusercontent.com/11976694/189704528-c608670d-4d22-4809-899c-2c21e6464036.jpg)

**Comment by AlCalzone** [comment]
This changed in v6:
https://github.com/sindresorhus/execa/releases/tag/v6.0.0

**Comment by Apollon77** [comment]
Thank you
